export const blockedUrls: string[] = [
	"youtube.com",
	"facebook.com",
	"instagram.com",
	"whatsapp.com",
	"x.com",
	"rutube",
	"kinopoisk.ru",
	"pikabu.ru",
	"buzzfeed.com",
	"9gag.com",
	"2ch.hk",
	"4pda.to",
	"4chan.org",
	"wikipedia.org",
	"reddit.com",
	"yahoo.com",
	"yahoo.co.jp",
	"amazon.com",
	"baidu.com",
	"tiktok.com",
	"netflix.com",
	"microsoftonline.com",
	"bing.com",
	"pornhub.com",
	"linkedin.com",
	"live.com",
	"naver.com",
	"dzen.ru",
	"xvideos.com",
	"pinterest.com",
	"bilibili.com",
	"twitch.tv",
	"twitter.com",
	"vk.com",
	"news.yahoo.co.jp",
	"xhamster.com",
	"mail.ru",
	"sharepoint.com",
	"samsung.com",
	"fandom.com",
	"globo.com",
	"canva.com",
	"xnxx.com",
	"duckduckgo.com",
	"t.me",
	"weather.com",
	"quora.com",
	"temu.com",
	"cnn.com",
	"zoom.us",
	"ebay.com",
	"roblox.com",
	"discord.com",
	"bbc.com",
	"apple.com",
	"espn.com",
	"adobe.com",
	"force.com",
	"salesforce.com",
	"aliexpress.com",
	"imdb.com",
	"ok.ru",
	"ozon.ru",
	"wildberries.ru",
	"booking.com",
	"whatsapp.net",
	"douyin.com",
	"hulu.com",
	"etsy.com",
	"indeed.com",
	"dropbox.com",
	"soundcloud.com",
	"stackexchange.com",
	"mediafire.com",
	"walmart.com",
	"nih.gov",
	"paypal.com",
	"bbc.co.uk",
	"archive.org",
	"zillow.com",
	"nytimes.com",
	"flipkart.com",
	"dailymotion.com",
	"investopedia.com",
	"target.com",
	"ikea.com",
	"tripadvisor.com",
	"foxnews.com",
	"weather.gov",
	"gamewith.jp",
	"gfycat.com",
	"gamer.com.tw",
	"gismeteo.ru",
	"gmx.net",
	"godaddy.com",
	"goo.ne.jp",
	"goodreads.com",
	"grammarly.com",
	"huffpost.com",
	"ign.com",
	"ikea.cn",
	"imgur.com",
	"instructure.com",
	"intuit.com",
	"investing.com",
	"japanpost.jp",
	"jstor.org",
	"kakaku.com",
	"kapanlagi.com",
	"kaskus.co.id",
	"khanacademy.org",
	"kompas.com",
	"lazada.sg",
	"leboncoin.fr",
	"lego.com",
	"lenovo.com",
	"lenta.ru",
	"lequipe.fr",
	"libero.it",
	"line.me",
	"livejournal.com",
	"livedoor.com",
	"livescore.com",
	"lowes.com",
	"macys.com",
	"mailchimp.com",
	"manoramaonline.com",
	"marriott.com",
	"mediafire.com",
	"medium.com",
	"mercadolivre.com.br",
	"mercadolibre.com.ar",
	"messenger.com",
	"metacafe.com",
	"microsoftonline.com",
	"microsoftstore.com",
	"microsofttranslator.com",
	"microsoftvirtualacademy.com",
	"microsoftvisualstudio.com",
	"microsoftwindows.com",
	"microsoftwindowsphone.com",
	"microsoftxbox.com",
	"microsoftxboxlive.com",
	"microsoftxboxone.com",
	"microsoftxboxsupport.com",
	"microsoftxboxwire.com",
	"microsoftxboxwireless.com",
	"microsoftxboxx.com",
	"microsoftyammer.com",
];

export const blockedOptions = [
	{label: "youtube.com", value: "youtube.com"},
	{label: "facebook.com", value: "facebook.com"},
	{label: "instagram.com", value: "instagram.com"},
	{label: "whatsapp.com", value: "whatsapp.com"},
	{label: "x.com", value: "x.com"},
	{label: "rutube", value: "rutube"},
	{label: "kinopoisk.ru", value: "kinopoisk.ru"},
	{label: "pikabu.ru", value: "pikabu.ru"},
	{label: "buzzfeed.com", value: "buzzfeed.com"},
	{label: "9gag.com", value: "9gag.com"},
	{label: "2ch.hk", value: "2ch.hk"},
	{label: "4pda.to", value: "4pda.to"},
	{label: "4chan.org", value: "4chan.org"},
	{label: "wikipedia.org", value: "wikipedia.org"},
	{label: "reddit.com", value: "reddit.com"},
	{label: "yahoo.com", value: "yahoo.com"},
	{label: "yahoo.co.jp", value: "yahoo.co.jp"},
	{label: "amazon.com", value: "amazon.com"},
	{label: "baidu.com", value: "baidu.com"},
	{label: "tiktok.com", value: "tiktok.com"},
	{label: "netflix.com", value: "netflix.com"},
	{label: "microsoftonline.com", value: "microsoftonline.com"},
	{label: "bing.com", value: "bing.com"},
	{label: "pornhub.com", value: "pornhub.com"},
	{label: "linkedin.com", value: "linkedin.com"},
	{label: "live.com", value: "live.com"},
	{label: "naver.com", value: "naver.com"},
	{label: "dzen.ru", value: "dzen.ru"},
	{label: "xvideos.com", value: "xvideos.com"},
	{label: "pinterest.com", value: "pinterest.com"},
	{label: "bilibili.com", value: "bilibili.com"},
	{label: "twitch.tv", value: "twitch.tv"},
	{label: "twitter.com", value: "twitter.com"},
	{label: "vk.com", value: "vk.com"},
	{label: "news.yahoo.co.jp", value: "news.yahoo.co.jp"},
	{label: "xhamster.com", value: "xhamster.com"},
	{label: "mail.ru", value: "mail.ru"},
	{label: "sharepoint.com", value: "sharepoint.com"},
	{label: "samsung.com", value: "samsung.com"},
	{label: "fandom.com", value: "fandom.com"},
	{label: "globo.com", value: "globo.com"},
	{label: "canva.com", value: "canva.com"},
	{label: "xnxx.com", value: "xnxx.com"},
	{label: "duckduckgo.com", value: "duckduckgo.com"},
	{label: "t.me", value: "t.me"},
	{label: "weather.com", value: "weather.com"},
	{label: "quora.com", value: "quora.com"},
	{label: "temu.com", value: "temu.com"},
	{label: "cnn.com", value: "cnn.com"},
	{label: "zoom.us", value: "zoom.us"},
	{label: "ebay.com", value: "ebay.com"},
	{label: "roblox.com", value: "roblox.com"},
	{label: "discord.com", value: "discord.com"},
	{label: "bbc.com", value: "bbc.com"},
	{label: "apple.com", value: "apple.com"},
	{label: "espn.com", value: "espn.com"},
	{label: "adobe.com", value: "adobe.com"},
	{label: "force.com", value: "force.com"},
	{label: "salesforce.com", value: "salesforce.com"},
	{label: "aliexpress.com", value: "aliexpress.com"},
	{label: "imdb.com", value: "imdb.com"},
	{label: "ok.ru", value: "ok.ru"},
	{label: "ozon.ru", value: "ozon.ru"},
	{label: "wildberries.ru", value: "wildberries.ru"},
	{label: "booking.com", value: "booking.com"},
	{label: "whatsapp.net", value: "whatsapp.net"},
	{label: "douyin.com", value: "douyin.com"},
	{label: "hulu.com", value: "hulu.com"},
	{label: "etsy.com", value: "etsy.com"},
	{label: "indeed.com", value: "indeed.com"},
	{label: "dropbox.com", value: "dropbox.com"},
	{label: "soundcloud.com", value: "soundcloud.com"},
	{label: "stackexchange.com", value: "stackexchange.com"},
	{label: "mediafire.com", value: "mediafire.com"},
	{label: "walmart.com", value: "walmart.com"},
	{label: "nih.gov", value: "nih.gov"},
	{label: "paypal.com", value: "paypal.com"},
	{label: "bbc.co.uk", value: "bbc.co.uk"},
	{label: "archive.org", value: "archive.org"},
	{label: "zillow.com", value: "zillow.com"},
	{label: "nytimes.com", value: "nytimes.com"},
	{label: "flipkart.com", value: "flipkart.com"},
	{label: "dailymotion.com", value: "dailymotion.com"},
	{label: "investopedia.com", value: "investopedia.com"},
	{label: "target.com", value: "target.com"},
	{label: "ikea.com", value: "ikea.com"},
	{label: "tripadvisor.com", value: "tripadvisor.com"},
	{label: "foxnews.com", value: "foxnews.com"},
	{label: "weather.gov", value: "weather.gov"},
	{label: "gamewith.jp", value: "gamewith.jp"},
	{label: "gfycat.com", value: "gfycat.com"},
	{label: "gamer.com.tw", value: "gamer.com.tw"},
	{label: "gismeteo.ru", value: "gismeteo.ru"},
	{label: "gmx.net", value: "gmx.net"},
	{label: "godaddy.com", value: "godaddy.com"},
	{label: "goo.ne.jp", value: "goo.ne.jp"},
	{label: "goodreads.com", value: "goodreads.com"},
	{label: "grammarly.com", value: "grammarly.com"},
	{label: "huffpost.com", value: "huffpost.com"},
	{label: "ign.com", value: "ign.com"},
	{label: "ikea.cn", value: "ikea.cn"},
	{label: "imgur.com", value: "imgur.com"},
	{label: "instructure.com", value: "instructure.com"},
	{label: "intuit.com", value: "intuit.com"},
	{label: "investing.com", value: "investing.com"},
	{label: "japanpost.jp", value: "japanpost.jp"},
	{label: "jstor.org", value: "jstor.org"},
	{label: "kakaku.com", value: "kakaku.com"},
	{label: "kapanlagi.com", value: "kapanlagi.com"},
	{label: "kaskus.co.id", value: "kaskus.co.id"},
	{label: "khanacademy.org", value: "khanacademy.org"},
	{label: "kompas.com", value: "kompas.com"},
	{label: "lazada.sg", value: "lazada.sg"},
	{label: "leboncoin.fr", value: "leboncoin.fr"},
	{label: "lego.com", value: "lego.com"},
	{label: "lenovo.com", value: "lenovo.com"},
	{label: "lenta.ru", value: "lenta.ru"},
	{label: "lequipe.fr", value: "lequipe.fr"},
	{label: "libero.it", value: "libero.it"},
	{label: "line.me", value: "line.me"},
	{label: "livejournal.com", value: "livejournal.com"},
	{label: "livedoor.com", value: "livedoor.com"},
	{label: "livescore.com", value: "livescore.com"},
	{label: "lowes.com", value: "lowes.com"},
	{label: "macys.com", value: "macys.com"},
	{label: "mailchimp.com", value: "mailchimp.com"},
	{label: "manoramaonline.com", value: "manoramaonline.com"},
	{label: "marriott.com", value: "marriott.com"},
	{label: "medium.com", value: "medium.com"},
	{label: "mercadolivre.com.br", value: "mercadolivre.com.br"},
	{label: "mercadolibre.com.ar", value: "mercadolibre.com.ar"},
	{label: "messenger.com", value: "messenger.com"},
	{label: "metacafe.com", value: "metacafe.com"},
	{label: "microsoftstore.com", value: "microsoftstore.com"},
	{label: "microsofttranslator.com", value: "microsofttranslator.com"},
	{label: "microsoftvirtualacademy.com", value: "microsoftvirtualacademy.com"},
	{label: "microsoftvisualstudio.com", value: "microsoftvisualstudio.com"},
	{label: "microsoftwindows.com", value: "microsoftwindows.com"},
	{label: "microsoftwindowsphone.com", value: "microsoftwindowsphone.com"},
	{label: "microsoftxbox.com", value: "microsoftxbox.com"},
	{label: "microsoftxboxlive.com", value: "microsoftxboxlive.com"},
	{label: "microsoftxboxone.com", value: "microsoftxboxone.com"},
	{label: "microsoftxboxsupport.com", value: "microsoftxboxsupport.com"},
	{label: "microsoftxboxwire.com", value: "microsoftxboxwire.com"},
	{label: "microsoftxboxwireless.com", value: "microsoftxboxwireless.com"},
	{label: "microsoftxboxx.com", value: "microsoftxboxx.com"},
	{label: "microsoftyammer.com", value: "microsoftyammer.com"},
];
